version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_Test_TBDProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: APSAProject
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/apsa
  gitUsername: kvv
  gitBranch: main
